version: '3.7'

services:
  chat-server:
    container_name: chat-server
    build:
      context: chat-server
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  chat-web-app:
    container_name: chat-web-app
    build:
      context: chat-web-app
      dockerfile: Dockerfile
    volumes:
      - '.:/chat-web-app/app'
      - '/chat-web-app/app/node_modules'
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true